Entrega Final Parte de Limpieza - Base de Datos : Videogames Sales and Ratings 2017

Mario Alberto Perez Barrera - A01799928

Marco Antonio Gonzalez Fernandez - A01799122

In [22]:
import pandas as pd
import numpy as np


# Cargar el archivo CSV
df = pd.read_csv('vgratings2017.csv')

# Inspección inicial
print("Primeras filas del conjunto de datos:")
df.head()

Primeras filas del conjunto de datos:

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.54,76.0,51.0,8.0,324.0,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.80,3.79,3.29,35.57,82.0,73.0,8.3,712.0,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.95,3.28,2.95,32.78,80.0,73.0,8.0,193.0,E
4,Pokemon Red/Pokemon Blue,G,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN

In [23]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17416 entries, 0 to 17415
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          17416 non-null  object
 1   Platform      17416 non-null  object
 2   Year          17408 non-null  float64
 3   Genre         17416 non-null  object
 4   Publisher     17415 non-null  object
 5   NA_Sales      17416 non-null  float64
 6   EU_Sales      17416 non-null  float64
 7   JP_Sales      17416 non-null  float64
 8   Other_Sales   17416 non-null  float64
 9   Global_Sales  17416 non-null  float64
 10  Critic_Score  8336 non-null   float64
 11  Critic_Count  8336 non-null   float64
 12  User_Score    7798 non-null   float64
 13  User_Count    7798 non-null   float64
 14  Rating        10252 non-null  object
dtypes: float64(10), object(5)
memory usage: 2.0+ MB

,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count
count,17408.000000,17416.000000,17416.000000,17416.000000,17416.000000,17416.000000,8336.000000,8336.000000,7798.000000,7798.000000
mean,2006.630859,0.254534,0.140727,0.075020,0.045908,0.516469,68.912548,26.192059,7.117056,162.672480
std,5.901598,0.800673,0.497341,0.303412,0.183932,1.526124,13.964937,18.991526,1.502410,562.837954
min,1976.000000,0.000000,0.000000,0.000000,0.000000,0.010000,13.000000,3.000000,0.000000,4.000000
25%,2003.000000,0.000000,0.000000,0.000000,0.000000,0.050000,60.000000,11.000000,6.400000,10.000000
50%,2008.000000,0.070000,0.020000,0.000000,0.010000,0.160000,71.000000,21.000000,7.500000,25.000000
75%,2011.000000,0.230000,0.100000,0.030000,0.030000,0.450000,79.000000,36.000000,8.200000,81.000000
max,2017.000000,41.360000,28.960000,10.220000,10.570000,82.540000,98.000000,113.000000,9.700000,10766.000000

In [24]:
# Revisión de valores faltantes
print(df.isnull().sum())

Name               0
Platform           0
Year               8
Genre              0
Publisher          1
NA_Sales           0
EU_Sales           0
JP_Sales           0
Other_Sales        0
Global_Sales       0
Critic_Score    9080
Critic_Count    9080
User_Score      9618
User_Count      9618
Rating          7164
dtype: int64

In [25]:
# Si hay duplicados, eliminarlos
df = df.drop_duplicates()

In [26]:

#Numericas
#Year_Of_Release, 5   NA_Sales   EU_Sales JP_Sales Other_Sales  Global_Sales Critic_Score Critic_Count User_Score User_Count       

df['Year'] = df['Year'].fillna(df['Year'].median())
df['NA_Sales'] = df['NA_Sales'].fillna(df['NA_Sales'].median())
df['EU_Sales'] = df['EU_Sales'].fillna(df['EU_Sales'].median())
df['JP_Sales'] = df['JP_Sales'].fillna(df['JP_Sales'].median())
df['Other_Sales'] = df['Other_Sales'].fillna(df['Other_Sales'].median())
df['Global_Sales'] = df['Global_Sales'].fillna(df['Global_Sales'].median())

#Criticas
df['Critic_Score'] = df['Critic_Score'].fillna(df['Critic_Score'].median())
df['Critic_Count'] = df['Critic_Count'].fillna(df['Critic_Count'].median())
df['User_Score'] = df['User_Score'].fillna(df['User_Score'].median())
df['User_Count'] = df['User_Count'].fillna(df['User_Count'].median())
   

#Categoricas
#Publisher, Rating

df['Publisher'] = df['Publisher'].fillna(df['Publisher'].mode()[0])
df['Rating'] = df['Rating'].fillna(df['Rating'].mode()[0])

In [27]:
#Checamos los datos limpiados
print(df.isnull().sum())

Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
Critic_Score    0
Critic_Count    0
User_Score      0
User_Count      0
Rating          0
dtype: int64

In [28]:
# Guardar los datos limpios en un nuevo archivo CSV
df.to_csv('clean_games.csv', index=False)